/**
 * Created by GIISO on 2017/8/25.
 */
/**
 * Created by GIISO on 2017/8/25.
 */

//在底部插入内容
var footerContent = ' <div class="top">'
    +'<ul class="inner">'
    +'<li style="background-image: url(images/footer-icon_03.jpg);">'
    +'<h5>贴心</h5>'
    +'<p>翻译全程<br>一对一陪护</p>'
    +'</li>'
    +'<li style="background-image: url(images/footer-icon_05.jpg);">'
    +'<h5>专业</h5>'
    +'<p>免费定制<br>就医方案</p>'
    +'</li>'
    +'<li style="background-image: url(images/footer-icon_07.jpg);">'
    +'<h5>实力</h5>'
    +'<p>16间医院<br>VIP通道</p>'
    +'</li>'
    +'<li style="background-image: url(images/footer-icon_09.jpg);">'
    +'<h5>全面</h5>'
    +'<p>知名医生<br>助孕建议</p>'
    +'</li>'
    +'<li style="background-image: url(images/footer-icon_11.jpg);">'
    +'<h5>保障</h5>'
    +'<p>品牌保障<br>名医推荐</p>'
    +'</li>'
    +'<li style="background-image: url(images/footer-icon_13.jpg);">'
    +'<h5>专注</h5>'
    +'<p>18项超越<br>同行标准</p>'
    +'</li>'
    +'<li style="background-image: url(images/footer-icon_15.jpg);">'
    +'<h5>诚信</h5>'
    +'<p>全程透明<br>无隐性消费</p>'
    +'</li>'
    +'<li style="background-image: url(images/footer-icon_17.jpg);">'
    +'<h5>肯定</h5>'
    +'<p>多年成功<br>案例经验</p>'
    +'</li>'
    +'</ul>'
    +'</div>'
    +'<div class="bottom">'
    +'<div class="inner">'
    +'<div class="left">'
    +'<img src="images/footer-logo_03.png">'
    +'</div>'
    +'<div class="right">'
    +'<div class="one">'
    +'<h4>快速导航</h4>'
    +'<a href="">费用明细</a>'
    +'<a href="">公司优势</a>'
    +'<a href="">服务流程</a>'
    +'<a href="">合作医院</a>'
    +'<a href="">合作医生</a>'
    +'<a href="">成功案列</a>'
    +'</div>'
    +'<div class="two">'
    +'<h4>公司地址</h4>'
    +'<h5>中国分公司</h5>'
    +'<p>杭州市江干区绿城财通中心<br>( 地铁1号线高沙站C出口 )</p>'
    +'<h5>巴塞罗那办事处</h5>'
    +'<p>广场弗兰切斯卡·马西亚7楼15 08029西班牙</p>'
    +'<h5>希腊办公室</h5>'
    +'<p>Plaieta Dimokratias 154629塞萨洛尼基 希腊</p>'
    +'<h5>基辅办事处</h5>'
    +'<p>Sichovykh Striltsiv街，60（719办公室）乌克兰</p>'
    +'<h5>莫斯科办事处</h5>'
    +'<p>立陶宛EJE 21一despacho 11 俄罗斯</p>'
    +'</div>'
    +'<div class="three">'
    +'<h4>联系方式</h4>'
    +'<h5>好孕热线<span>15381005201</span></h5>'
    +'<h5>QQ&nbsp;微信<span>151363970</span></h5>'
    +'<p>杭州上范健康管理有限公司</p>'
    +'<ul>'
    +'<li>'
    +'<img src="images/erweima-guanfang.jpg">'
    +'<p>官方微信</p>'
    +'</li>'
    +'<li style="float: right">'
    +'<img src="images/erweima-dazhonghua.jpg">'
    +'<p>大中华区<br>客户代表微信</p>'
    +'</li>'
    +'</ul>'
    +'</div>'
    +'</div>'
    +'</div>'
    +'</div>';

$(".footer").html(footerContent);