/**
 * Created by GIISO on 2017/8/25.
 */

//在头部插入内容
var headerContent = '<div class="top">'
    + '<div class="inner">'
    + '<p class="left">中国持有不孕不育生殖医疗专业咨询服务机构</p>'
    + '<p class="right">QQ 微信:<span style="margin-right: 25px;">151363970</span> 好孕热线:<span>15381005201</span></p>'
    + '</div>'
    + '</div>'
    + '<div class="bottom">'
    + '<div class="inner">'
    + '<div class="logo"><img src="images/logo_03.png"></div>'
    + '<ul class="nav clearfix">'
    + '<li class="active">'
    + '<a href="index.html">'
    + '<p>首页</p>'
    + '<span>HOME</span>'
    + '</a>'
    + '</li>'
    + '<li>'
    + '<a href="">'
    + '<p>公司优势</p>'
    + '<span>advantage</span>'
    + '</a>'
    + '</li>'
    + '<li>'
    + '<a href="">'
    + '<p>费用明细</p>'
    + '<span>Details</span>'
    + '</a>'
    + '</li>'
    + '<li class="small-nav">'
    + '<a href="">'
    + '<p>赴欧孕育须知</p>'
    + '<span>Notice</span>'
    + '</a>'
    + '<i></i>'
    + '<div class="s-nav">'
    + '<a href="">试管婴儿服务</a>'
    + '<a href="">冻卵冻精服务</a>'
    + '<a href="">试管婴儿技术</a>'
    + '<a href="">服务流程咨询</a>'
    + '</div>'
    + '</li>'
    + '<li>'
    + '<a href="">'
    + '<p>成功案例</p>'
    + '<span>case</span>'
    + '</a>'
    + '</li>'
    + '<li class="small-nav">'
    + '<a href="">'
    + '<p>合作医院医生</p>'
    + '<span>doctor</span>'
    + '</a>'
    + '<i></i>'
    + '<div class="s-nav">'
    + '<a href="">合作医院</a>'
    + '<a href="">合作医生</a>'
    + '</div>'
    + '</li>'
    + '<li>'
    + '<a href="">'
    + '<p>联系上范</p>'
    + '<span>contact</span>'
    + '</a>'
    + '</li>'
    + '</ul>'
    + '</div>'
    + '</div>';

$(".header").html(headerContent);